# Generated by Django 5.0.6 on 2024-08-21 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_tipo_user',
            field=models.ForeignKey(default='cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='ski_app.tipousuario'),
        ),
    ]
